# Generated by Django 2.2.13 on 2020-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='date_started',
            field=models.DateField(blank=True),
        ),
    ]
