# Generated by Django 2.2.13 on 2020-07-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200706_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=50)),
                ('date_completed', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='qualification',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
